### ISSUE TITLE
frontend: clean up admin panel

### ISSUE THREAD

**Issue by bsilkyn** [SELab-2/UGent-7#356]
The admin panel is quite sloppy right now. A cleanup is desperately needed.

- [x] Refine layout
- [x] Make layout adaptable to small screens
- [x] Show docker image status

**Comment by DeLany123** [comment]
@EwoutV @bsilkyn It is not obvious now to change the public field of a docker image
![image](https://github.com/SELab-2/UGent-7/assets/67026331/e49af944-e9b7-4bb6-82a1-3782f72ca216)

**Comment by bsilkyn** [comment]
> @EwoutV @bsilkyn It is not obvious now to change the public field of a docker image ![image](https://private-user-images.githubusercontent.com/67026331/327780848-e49af944-e9b7-4bb6-82a1-3782f72ca216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODU2NjUsIm5iZiI6MTcxNTc4NTM2NSwicGF0aCI6Ii82NzAyNjMzMS8zMjc3ODA4NDgtZTQ5YWY5NDQtZTliNy00YmI2LTgyYTEtMzc4MmY3MmNhMjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MmY0Njg2MDg5YmQzOGQ4YzJkOGZlYjUzNDE4NGI1M2MwYTFmYWM1NGI2NDEwYWEwZGJhOTlhYTUyNWYwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5ACePawe6cRTLsSZiG8QEv3-XM5X3x8Feh-_mH7Rso)

This has been fixed in my new pr
