### ISSUE TITLE
Tests: Get Cypress tests running again 

### ISSUE THREAD

**Issue by DeLany123** [SELab-2/UGent-7#405]
#397 in test.sh line 95 
![image](https://github.com/SELab-2/UGent-7/assets/67026331/73bb2758-a073-4ea9-ba35-a0a9892e1cb2)
https://github.com/SELab-2/UGent-7/blob/6755a5984a1c92a41ef4cd4da30d85e8c6afbde3/test.sh#L95

**Comment by tyboro2002** [comment]
Isn't this already done?
